// Download every external image URL referenced in /data and /app source
// files into /public/images/wikimedia/. Optimises each to a max-1280px-wide
// JPEG (preserves PNG for the few that need transparency). Then writes a
// local-path map that lib/placeholder.ts uses to serve images from the
// Vercel CDN instead of upload.wikimedia.org.
//
// Why: hotlinking from upload.wikimedia.org is unreliable in production.
// Wikimedia rate-limits aggressive consumers; some Vercel deployments
// see intermittent 429s + image-optimisation failures. Local copies are
// served from the same edge as the rest of the site — predictable, fast.

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import sharp from "sharp";

const PUBLIC_DIR = "public/images/wikimedia";
const MAP_FILE = "lib/imageMap.ts";

const sources = [
  "data/cities.ts",
  "data/carTypes.ts",
  "data/useCases.ts",
  "data/guides.ts",
  "app/tourist-car-rental/page.tsx",
  "app/wedding-car-rental/page.tsx",
  "app/airport-pickup/page.tsx",
  "app/northern-areas-tours/page.tsx",
  "app/corporate-monthly/page.tsx",
  "app/self-drive-rental/page.tsx",
  "app/tourist-packages/page.tsx",
  "components/home/ForTourists.tsx",
];

// Pull every Wikimedia URL from the source files.
const urls = new Set();
for (const file of sources) {
  if (!fs.existsSync(file)) continue;
  const text = fs.readFileSync(file, "utf8");
  // Match upload.wikimedia.org URLs with no quote/whitespace.
  const matches = text.match(/https:\/\/upload\.wikimedia\.org\/[^"'\s)]+/g) || [];
  matches.forEach((u) => urls.add(u));
}
console.log(`Found ${urls.size} unique Wikimedia URLs across ${sources.length} files`);

fs.mkdirSync(PUBLIC_DIR, { recursive: true });

function stableFilename(url) {
  // Hash for collision-free filenames, keep an inferred extension.
  const hash = createHash("sha1").update(url).digest("hex").slice(0, 12);
  const m = url.match(/\.([a-zA-Z]{3,4})(?:$|[?#])/);
  const ext = (m ? m[1] : "jpg").toLowerCase();
  // Normalise to jpg/png/webp for the optimiser; .JPG → .jpg etc.
  const safe = ["jpg", "jpeg", "png", "webp"].includes(ext) ? ext : "jpg";
  return `${hash}.${safe}`;
}

const map = {};
let downloaded = 0;
let cached = 0;
let failed = 0;

for (const url of urls) {
  const filename = stableFilename(url);
  const outPath = path.join(PUBLIC_DIR, filename);
  const publicPath = `/images/wikimedia/${filename}`;

  if (fs.existsSync(outPath)) {
    map[url] = publicPath;
    cached++;
    continue;
  }

  // Full-res Wikimedia URLs (no /thumb/) get rate-limited harder. Build a
  // thumb-form fallback up front so we can retry through Wikimedia's CDN.
  function thumbifyUrl(u) {
    const m = u.match(/^(https:\/\/upload\.wikimedia\.org\/wikipedia\/(?:commons|en))\/([a-f0-9])\/([a-f0-9]{2})\/([^/?#]+)$/);
    if (!m) return null;
    const [, prefix, a, ab, file] = m;
    return `${prefix}/thumb/${a}/${ab}/${file}/1280px-${file}`;
  }

  async function tryFetch(u) {
    return fetch(u, {
      headers: { "User-Agent": "RentalSawari-Setup/1.0 (one-time mirror)" },
    });
  }

  try {
    let res = await tryFetch(url);
    if (res.status === 429 || res.status === 403) {
      const alt = thumbifyUrl(url);
      if (alt) {
        await new Promise((r) => setTimeout(r, 1500));
        res = await tryFetch(alt);
      }
    }
    if (!res.ok) {
      console.log(`  FAIL ${res.status} ${url.slice(0, 80)}`);
      failed++;
      continue;
    }
    const buf = Buffer.from(await res.arrayBuffer());

    // Re-encode at max 1280px wide. Sharp auto-detects the source format.
    const isPng = filename.endsWith(".png");
    const pipeline = sharp(buf).resize({ width: 1280, withoutEnlargement: true });
    const finalBuf = isPng
      ? await pipeline.png({ compressionLevel: 9 }).toBuffer()
      : await pipeline.jpeg({ quality: 82, mozjpeg: true }).toBuffer();
    fs.writeFileSync(outPath, finalBuf);
    map[url] = publicPath;
    downloaded++;
    console.log(
      `  ↓ ${filename}  (${(finalBuf.length / 1024).toFixed(0)} KB)  ← ${url
        .slice(0, 70)
        .replace(/^https:\/\/upload\.wikimedia\.org\/wikipedia\//, "…/")}`,
    );
  } catch (e) {
    console.log(`  ERR ${e.message}  ${url.slice(0, 60)}`);
    failed++;
  }

  // Polite delay so we don't trip Wikimedia rate limits. Bumped to 4s after
  // observing 429s at faster cadence.
  await new Promise((r) => setTimeout(r, 4000));
}

console.log(
  `\nDone. downloaded=${downloaded}  cached=${cached}  failed=${failed}`,
);

// Emit lib/imageMap.ts so placeholder.ts can swap Wikimedia URLs → local paths.
const sorted = Object.keys(map).sort();
const lines = [];
lines.push("// Auto-generated by scripts/downloadImages.mjs.");
lines.push("// Do not hand-edit — re-run the script after any data/* image URL change.");
lines.push(`// Last generated: ${new Date().toISOString()}`);
lines.push("");
lines.push("export const imageMap: Record<string, string> = {");
for (const k of sorted) {
  lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`);
}
lines.push("};");
lines.push("");
fs.writeFileSync(MAP_FILE, lines.join("\n"));
console.log(`Wrote ${MAP_FILE} with ${sorted.length} entries`);
